[versions]
## Gradle API
fix-javadoc = "1.19" # https://github.com/mfnalex/gradle-fix-javadoc-plugin
feather = "0.8.2" # https://github.com/ryderbelserion/Feather
shadow = "9.6.1" # https://github.com/GradleUp/shadow

## Better Annotations
jspecify = "1.0.0" # https://jspecify.dev/docs/using/

## File API
snakeyaml = "2.8.0"
jackson = "2.20.0"
gson = "2.8.0"

## Other API
assertj = "3.27.7"
autoValue = "1.11.1"
geantyref = "1.3.16"
junit = "5.14.2"

## Publish Url
url = "https://repo.crazycrew.us/releases"
[libraries]
# https://github.com/ryderbelserion/Feather
feather-patcher = { module = "com.ryderbelserion.feather.patcher:com.ryderbelserion.feather.patcher.gradle.plugin", version.ref = "feather" }

# https://github.com/mfnalex/gradle-fix-javadoc-plugin/
fix-javadoc = { module = "com.jeff-media.fix-javadoc-plugin:com.jeff-media.fix-javadoc-plugin.gradle.plugin", version.ref = "fix-javadoc" }

# https://github.com/ryderbelserion/Feather
feather-core = { module = "com.ryderbelserion.feather.core:com.ryderbelserion.feather.core.gradle.plugin", version.ref = "feather" }

# https://github.com/GradleUp/shadow
shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }

jackson = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson"}
# https://github.com/ryderbelserion/SnakeYAML
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
# https://github.com/google/gson
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# https://jspecify.dev/docs/using/
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

# Other API
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

autoValue = { module = "com.google.auto.value:auto-value", version.ref = "autoValue" }
autoValue-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "autoValue" }

guava = "com.google.guava:guava:33.5.0-jre"

junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }

geantyref = { module = "io.leangen.geantyref:geantyref", version.ref = "geantyref" }
option = { module = "net.kyori:option", version = "1.1.0" }

[bundles]
build = [
    "feather-patcher",
    "feather-core",

    "fix-javadoc",
    "shadow"
]